import * as stylex from '@stylexjs/stylex';

export const styles = stylex.create({
  page: { backgroundColor: '#f4f0e7', minHeight: '100vh', padding: 'clamp(22px, 4vw, 56px)' },
  hero: {
    display: 'grid',
    gap: '28px',
    gridTemplateColumns: 'minmax(0, 1.35fr) minmax(280px, 0.65fr)',
    marginBottom: '30px',
    marginLeft: 'auto',
    marginRight: 'auto',
    maxWidth: '1180px',
    '@media (max-width: 760px)': { gridTemplateColumns: '1fr' },
  },
  eyebrow: {
    color: '#d84b2b',
    fontSize: '0.74rem',
    fontWeight: 800,
    letterSpacing: '0.16em',
    marginBottom: '12px',
    marginTop: 0,
    textTransform: 'uppercase',
  },
  title: {
    color: '#18332e',
    fontFamily: 'Georgia, Cambria, "Times New Roman", serif',
    fontSize: 'clamp(2.8rem, 7vw, 6.5rem)',
    fontWeight: 500,
    letterSpacing: '-0.055em',
    lineHeight: 0.9,
    margin: 0,
    maxWidth: '850px',
  },
  intro: { color: '#52645f', fontSize: 'clamp(1rem, 2vw, 1.18rem)', lineHeight: 1.65, marginBottom: 0, marginTop: '24px', maxWidth: '680px' },
  controls: { alignSelf: 'end', backgroundColor: '#18332e', borderRadius: '18px', boxShadow: '0 18px 45px rgba(24, 51, 46, 0.16)', padding: '22px' },
  label: { color: '#e9ece5', display: 'block', fontSize: '0.82rem', fontWeight: 700, marginBottom: '9px' },
  intervalFields: { display: 'grid', gap: '9px', gridTemplateColumns: '1fr 1fr' },
  field: { display: 'block', minWidth: 0 },
  fieldLabel: { color: '#b9c8c3', display: 'block', fontSize: '0.68rem', fontWeight: 750, marginBottom: '5px', textTransform: 'uppercase' },
  input: {
    backgroundColor: '#fffdf8',
    borderColor: 'transparent',
    borderRadius: '10px',
    borderStyle: 'solid',
    borderWidth: '2px',
    color: '#18332e',
    fontSize: '1.15rem',
    fontWeight: 750,
    minWidth: 0,
    padding: '10px 12px',
    width: '100%',
    ':focus': { borderColor: '#f15a37', outline: 'none' },
  },
  primaryButton: { backgroundColor: '#f15a37', borderWidth: 0, borderRadius: '10px', color: '#fffdf8', cursor: 'pointer', fontWeight: 800, marginTop: '10px', minHeight: '42px', padding: '0 18px', whiteSpace: 'nowrap', width: '100%', ':hover': { backgroundColor: '#d84b2b' } },
  presets: { display: 'flex', gap: '8px', marginTop: '12px' },
  preset: {
    backgroundColor: 'transparent',
    borderColor: '#678079',
    borderRadius: '999px',
    borderStyle: 'solid',
    borderWidth: '1px',
    color: '#cfd8d3',
    cursor: 'pointer',
    fontSize: '0.78rem',
    fontWeight: 700,
    padding: '5px 11px',
    ':hover': { borderColor: '#fffdf8', color: '#fffdf8' },
  },
  presetActive: { backgroundColor: '#fffdf8', borderColor: '#fffdf8', color: '#18332e' },
  modeLabel: { color: '#e9ece5', display: 'block', fontSize: '0.82rem', fontWeight: 700, marginBottom: '8px', marginTop: '18px' },
  modeSwitch: { backgroundColor: '#294740', borderRadius: '10px', display: 'grid', gap: '4px', gridTemplateColumns: '1fr 1fr', padding: '4px' },
  modeButton: { backgroundColor: 'transparent', borderRadius: '7px', borderWidth: 0, color: '#cfd8d3', cursor: 'pointer', fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace', fontSize: '0.78rem', fontWeight: 750, padding: '8px' },
  modeButtonActive: { backgroundColor: '#fffdf8', color: '#18332e' },
  error: { color: '#ffb9a9', fontSize: '0.78rem', marginBottom: 0, marginTop: '10px' },
  plotCard: { backgroundColor: '#fffdf8', borderRadius: '24px', boxShadow: '0 22px 70px rgba(48, 55, 48, 0.11)', marginLeft: 'auto', marginRight: 'auto', maxWidth: '1180px', padding: 'clamp(18px, 3.5vw, 42px)' },
  plotHeader: { alignItems: 'end', display: 'flex', gap: '24px', justifyContent: 'space-between', '@media (max-width: 720px)': { alignItems: 'start', flexDirection: 'column' } },
  plotLabel: { color: '#d84b2b', fontSize: '0.72rem', fontWeight: 800, letterSpacing: '0.12em', margin: 0, textTransform: 'uppercase' },
  plotTitle: { color: '#18332e', fontFamily: 'Georgia, Cambria, serif', fontSize: 'clamp(2rem, 5vw, 3.5rem)', fontWeight: 500, marginBottom: 0, marginTop: '4px' },
  stats: { display: 'flex', flexWrap: 'wrap', gap: '9px' },
  stat: { backgroundColor: '#f2eee5', borderRadius: '11px', minWidth: '90px', padding: '9px 12px' },
  statValue: { color: '#18332e', display: 'block', fontSize: '1.05rem', fontWeight: 800 },
  statLabel: { color: '#687670', display: 'block', fontSize: '0.67rem', fontWeight: 700, marginTop: '2px', textTransform: 'uppercase' },
  progressBlock: { backgroundColor: '#e8e4da', borderRadius: '11px', marginTop: '18px', padding: '10px 12px' },
  progressLabel: { color: '#52645f', display: 'flex', fontSize: '0.76rem', fontWeight: 750, justifyContent: 'space-between', marginBottom: '7px' },
  progressTrack: { backgroundColor: '#d0d5cc', borderRadius: '999px', height: '8px', overflow: 'hidden' },
  progressFill: { backgroundColor: '#f15a37', borderRadius: '999px', height: '100%', transitionDuration: '120ms', transitionProperty: 'width', transitionTimingFunction: 'ease-out' },
  notice: { backgroundColor: '#fff1eb', borderRadius: '10px', color: '#9b3d27', fontSize: '0.84rem', marginBottom: 0, marginTop: '18px', padding: '10px 13px' },
  plotWrap: { marginLeft: 'auto', marginRight: 'auto', marginTop: '20px', maxWidth: '820px' },
});
