import * as stylex from '@stylexjs/stylex';

// Chains-page styles; the shared page shell stays in appStyles.stylex.js.
export const chainStyles = stylex.create({
  detailCard: { backgroundColor: '#f2eee5', borderRadius: '16px', marginTop: '18px', padding: '16px 18px' },
  detailHead: { alignItems: 'start', display: 'flex', gap: '14px', justifyContent: 'space-between' },
  detailSeed: { color: '#18332e', fontSize: '1.6rem', fontWeight: 800, marginBottom: 0, marginTop: '2px' },
  detailBody: { color: '#4c5b56', fontSize: '0.88rem', lineHeight: 1.6, marginBottom: 0, marginTop: '10px' },
  detailClose: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderColor: '#a8b5b0',
    borderRadius: '999px',
    borderStyle: 'solid',
    borderWidth: '1px',
    color: '#4c5b56',
    cursor: 'pointer',
    display: 'inline-flex',
    fontSize: '0.74rem',
    fontWeight: 700,
    justifyContent: 'center',
    minHeight: '44px',
    padding: '0 14px',
    ':hover': { backgroundColor: '#18332e', borderColor: '#18332e', color: '#fffdf8' },
  },
  selectHint: { color: '#5f6c66', fontSize: '0.8rem', marginBottom: 0, marginTop: '12px' },
  chainButton: {
    backgroundColor: '#f2eee5',
    borderRadius: '12px',
    borderWidth: 0,
    cursor: 'pointer',
    display: 'block',
    padding: '12px 14px',
    textAlign: 'start',
    width: '100%',
    ':hover': { backgroundColor: '#e8e2d5' },
  },
  chainButtonActive: { backgroundColor: '#e2ddcd', outlineColor: '#18332e', outlineStyle: 'solid', outlineWidth: '2px' },
  explainerCard: {
    backgroundColor: '#18332e',
    borderRadius: '24px',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: '22px',
    maxWidth: '1180px',
    padding: 'clamp(22px, 3.5vw, 42px)',
  },
  explainerTitle: {
    color: '#fffdf8',
    fontFamily: 'Georgia, Cambria, "Times New Roman", serif',
    fontSize: 'clamp(1.6rem, 3.4vw, 2.4rem)',
    fontWeight: 500,
    letterSpacing: '-0.03em',
    margin: 0,
  },
  explainerLead: { color: '#dfe5e0', fontSize: 'clamp(0.98rem, 1.6vw, 1.1rem)', lineHeight: 1.65, marginBottom: 0, marginTop: '14px', maxWidth: '760px' },
  explainerPoints: { display: 'grid', gap: '22px', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', marginTop: '26px' },
  explainerPointTitle: { color: '#f8a58e', fontSize: '0.78rem', fontWeight: 800, letterSpacing: '0.1em', margin: 0, textTransform: 'uppercase' },
  explainerBody: { color: '#c8d3ce', fontSize: '0.92rem', lineHeight: 1.7, marginBottom: 0, marginTop: '10px', maxWidth: '760px' },
  explainerConclusion: {
    borderColor: '#f15a37',
    borderLeftStyle: 'solid',
    borderLeftWidth: '3px',
    color: '#fffdf8',
    fontSize: 'clamp(1rem, 1.8vw, 1.15rem)',
    lineHeight: 1.6,
    marginBottom: 0,
    marginTop: '26px',
    maxWidth: '760px',
    paddingLeft: '16px',
  },
  ruleGroup: { display: 'grid', gap: '6px', marginTop: '18px' },
  ruleButton: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderColor: '#678079',
    borderRadius: '9px',
    borderStyle: 'solid',
    borderWidth: '1px',
    color: '#cfd8d3',
    cursor: 'pointer',
    display: 'flex',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: '0.8rem',
    fontWeight: 700,
    justifyContent: 'center',
    minHeight: '44px',
    padding: '0 12px',
    ':hover': { borderColor: '#fffdf8', color: '#fffdf8' },
  },
  ruleButtonActive: { backgroundColor: '#fffdf8', borderColor: '#fffdf8', color: '#18332e' },
  ruleNote: { color: '#b9c8c3', fontSize: '0.74rem', lineHeight: 1.55, marginBottom: 0, marginTop: '10px' },
  emptyState: { backgroundColor: '#f2eee5', borderRadius: '14px', marginTop: '20px', padding: '22px' },
  emptyTitle: { color: '#18332e', fontSize: '1.05rem', fontWeight: 800, margin: 0 },
  emptyBody: { color: '#52645f', fontSize: '0.88rem', lineHeight: 1.6, marginBottom: 0, marginTop: '8px' },
  chainList: { display: 'grid', gap: '10px', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', listStyle: 'none', marginTop: '18px', padding: 0 },
  chainItem: { backgroundColor: '#f2eee5', borderRadius: '12px', padding: '12px 14px' },
  chainSeed: { alignItems: 'baseline', display: 'flex', gap: '9px', justifyContent: 'space-between' },
  chainSeedValue: { color: '#18332e', fontSize: '1.1rem', fontWeight: 800 },
  chainDepth: { color: '#535e59', fontSize: '0.68rem', fontWeight: 700, textTransform: 'uppercase' },
  chainSteps: { display: 'grid', gap: '3px', marginTop: '8px' },
  chainStep: { color: '#52645f', fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace', fontSize: '0.74rem' },
});
